# Generated by Django 4.1.7 on 2023-03-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=100)),
                ('estimated_time', models.IntegerField()),
                ('start_date', models.DateField()),
                ('completion_date', models.DateField()),
            ],
            options={
                'db_table': 'project',
            },
        ),
    ]
